services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=barcode_wms
      - DB_USER=wms_user
      - DB_PASS=wms_password
    networks:
      - wms-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: barcode_wms
      MYSQL_USER: wms_user
      MYSQL_PASSWORD: wms_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - wms-network

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root_password
    depends_on:
      - db
    networks:
      - wms-network

volumes:
  mysql_data:

networks:
  wms-network:
    driver: bridge