services:
  webinterface-simple:
    build:
      context: .
      dockerfile: Dockerfile.simple
    image: multibarcode-webinterface:simple
    container_name: multibarcode-webinterface-simple
    ports:
      - "3500:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s